name: Update public-ip for personal homeassistant domain

on:
  workflow_dispatch:
  push:   # only if 'ip.txt' file changes
    paths:
      - ip.txt

jobs: 
  update:
    runs-on: ubuntu-latest
    steps:

      - name: checkout current repo
        uses: actions/checkout@v3
        
      - name: checkout longavailable/longavailable.github.io repo
        uses: actions/checkout@v3
        with: 
          repository: longavailable/longavailable.github.io
          path: site
      
      - name: update page
        run: sed -i -r 's/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'/"$(cat ip.txt)"/ site/myCollections/_separate-pages/homeassistant.md

      - name: commit and push site repo
        uses: longavailable/simple-push-action@main
        with:
          repository: longavailable/longavailable.github.io
          path: site
          message: "Update public-ip from Action `date`"
